"""initial schema baseline

Revision ID: 3a255adfea55
Revises: 
Create Date: 2026-03-14 10:21:24.778199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a255adfea55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel_publish_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('default_title_template', sa.String(), nullable=True),
    sa.Column('default_description_template', sa.Text(), nullable=True),
    sa.Column('default_hashtags', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_publish_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_publish_targets_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_name', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('state_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)

    op.create_table('reel_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('clip_duration', sa.Integer(), nullable=True),
    sa.Column('pan_direction', sa.String(), nullable=True),
    sa.Column('pan_speed', sa.Float(), nullable=True),
    sa.Column('ai_config', sa.JSON(), nullable=True),
    sa.Column('overlay_style', sa.String(), nullable=True),
    sa.Column('font_family', sa.String(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('text_color', sa.String(), nullable=True),
    sa.Column('text_shadow', sa.Boolean(), nullable=True),
    sa.Column('text_background', sa.String(), nullable=True),
    sa.Column('text_position_y', sa.Float(), nullable=True),
    sa.Column('publish_mode', sa.String(), nullable=True),
    sa.Column('schedule_times', sa.JSON(), nullable=True),
    sa.Column('default_title_template', sa.String(), nullable=True),
    sa.Column('default_description_template', sa.Text(), nullable=True),
    sa.Column('default_hashtags', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_templates_id'), ['id'], unique=False)

    op.create_table('reel_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('source_clip_path', sa.String(), nullable=True),
    sa.Column('portrait_clip_path', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('generated_headlines', sa.JSON(), nullable=True),
    sa.Column('scheduled_capture_at', sa.DateTime(), nullable=True),
    sa.Column('recurring_schedule', sa.JSON(), nullable=True),
    sa.Column('auto_publish', sa.Boolean(), nullable=True),
    sa.Column('publish_platform', sa.String(), nullable=True),
    sa.Column('publish_title', sa.String(), nullable=True),
    sa.Column('publish_description', sa.Text(), nullable=True),
    sa.Column('publish_tags', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('capture_started_at', sa.DateTime(), nullable=True),
    sa.Column('capture_completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['reel_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_posts_id'), ['id'], unique=False)

    op.create_table('reelforge_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openai_api_key_enc', sa.String(), nullable=True),
    sa.Column('openai_model', sa.String(), nullable=True),
    sa.Column('system_prompt', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('default_template_id', sa.Integer(), nullable=True),
    sa.Column('tempest_api_url', sa.String(), nullable=True),
    sa.Column('weather_enabled', sa.Boolean(), nullable=True),
    sa.Column('youtube_client_id', sa.String(), nullable=True),
    sa.Column('youtube_client_secret_enc', sa.String(), nullable=True),
    sa.Column('youtube_refresh_token_enc', sa.String(), nullable=True),
    sa.Column('youtube_connected', sa.Boolean(), nullable=True),
    sa.Column('youtube_channel_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_template_id'], ['reel_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reelforge_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reelforge_settings_id'), ['id'], unique=False)

    op.create_table('reel_capture_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('trigger_mode', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['reel_posts.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_capture_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_capture_queue_id'), ['id'], unique=False)

    op.create_table('reel_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('platform_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['reel_posts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['reel_publish_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_exports_id'), ['id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)

    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(), nullable=True))
        batch_op.alter_column('camera_preset_token',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('streaming_destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('enable_watchdog', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('youtube_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('youtube_stream_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('youtube_broadcast_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('youtube_watch_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('watchdog_check_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watchdog_enable_frame_probe', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('watchdog_enable_daily_reset', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('watchdog_daily_reset_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('youtube_oauth_code_verifier', sa.String(), nullable=True))
        batch_op.alter_column('youtube_oauth_client_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_client_secret_enc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_redirect_uri',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_refresh_token_enc',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_channel_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_streams_id'), ['id'], unique=False)
        batch_op.create_foreign_key(None, 'presets', ['preset_id'], ['id'])

    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broadcast_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('broadcast_description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('broadcast_tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('broadcast_privacy', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('broadcast_category_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('broadcast_thumbnail_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelines', schema=None) as batch_op:
        batch_op.drop_column('broadcast_thumbnail_enabled')
        batch_op.drop_column('broadcast_category_id')
        batch_op.drop_column('broadcast_privacy')
        batch_op.drop_column('broadcast_tags')
        batch_op.drop_column('broadcast_description')
        batch_op.drop_column('broadcast_title')

    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_streams_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('streaming_destinations', schema=None) as batch_op:
        batch_op.alter_column('youtube_oauth_channel_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_refresh_token_enc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_redirect_uri',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_client_secret_enc',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('youtube_oauth_client_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('youtube_oauth_code_verifier')
        batch_op.drop_column('watchdog_daily_reset_hour')
        batch_op.drop_column('watchdog_enable_daily_reset')
        batch_op.drop_column('watchdog_enable_frame_probe')
        batch_op.drop_column('watchdog_check_interval')
        batch_op.drop_column('youtube_watch_url')
        batch_op.drop_column('youtube_broadcast_id')
        batch_op.drop_column('youtube_stream_id')
        batch_op.drop_column('youtube_api_key')
        batch_op.drop_column('enable_watchdog')
        batch_op.drop_column('channel_id')

    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.alter_column('camera_preset_token',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('thumbnail_path')

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('city')
        batch_op.drop_column('state_name')

    with op.batch_alter_table('reel_exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_exports_id'))

    op.drop_table('reel_exports')
    with op.batch_alter_table('reel_capture_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_capture_queue_id'))

    op.drop_table('reel_capture_queue')
    with op.batch_alter_table('reelforge_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reelforge_settings_id'))

    op.drop_table('reelforge_settings')
    with op.batch_alter_table('reel_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_posts_id'))

    op.drop_table('reel_posts')
    with op.batch_alter_table('reel_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_templates_id'))

    op.drop_table('reel_templates')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('reel_publish_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_publish_targets_id'))

    op.drop_table('reel_publish_targets')
    # ### end Alembic commands ###
