name: Frontend ARM Build

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (ARM64)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: docker.io/nickdnj/vistter-frontend:latest
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL || 'http://localhost:8000/api' }}


